// Level 6 - "The Sixfold Weave"
//
// Returns to Level 2's fifteen-piece scale with a different construction:
// a regular side-2 hexagon on the triangular lattice, tiled by nine rhombi
// and six triangles. Canonical lattice-edge ownership determines every
// neighbor and outside edge; the intended line is a Hamiltonian cycle.
//
// scripts/verify-level6.mjs exhaustively finds 3 Hamiltonian cycles (quotient
// reversal), of which exactly 1 matches this inventory after identical piece
// labels and redundant straight-piece rotations are quotiented. Its 15
// solution-supported starts occupy 9 distinct orbits under the hexagon's D6
// symmetries, while the completed groove has no nonidentity D6 symmetry.
export const level6 = {
  id: "sixfold-weave",
  number: 6,
  title: "The Sixfold Weave",
  shortTitle: "Sixfold Weave",
  description:
    "Fifteen stones fill a six-sided court. Follow the bends that open one path without teaching it to mirror itself.",
  board: {
    macroCenter: [0, 0],
    center: [500, 265],
    scale: 115,
    side: 2,
  },
  endpointMode: "center",
  hint: { pieceId: "r-straight-a", slotId: "R02", rotation: 0 },
  slots: [
    {
      id: "R01",
      shape: "rhombus",
      center: [-1.25, -0.4330127],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [2],
      neighbors: { R02: 3, R04: 0, T01: 1 },
    },
    {
      id: "R02",
      shape: "rhombus",
      center: [-1.25, 0.4330127],
      angle: 60,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [3],
      neighbors: { R01: 2, R03: 0, T02: 1 },
    },
    {
      id: "R03",
      shape: "rhombus",
      center: [-0.75, 1.299038],
      angle: 60,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R02: 2, R05: 1 },
    },
    {
      id: "R04",
      shape: "rhombus",
      center: [-0.25, -0.4330127],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [],
      neighbors: { R01: 2, R06: 1, R07: 0, T02: 3 },
    },
    {
      id: "R05",
      shape: "rhombus",
      center: [0.25, 1.299038],
      angle: 60,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [0],
      neighbors: { R03: 3, R08: 1, T03: 2 },
    },
    {
      id: "R06",
      shape: "rhombus",
      center: [-0.25, -1.299038],
      angle: 60,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [2],
      neighbors: { R04: 0, T01: 3, T04: 1 },
    },
    {
      id: "R07",
      shape: "rhombus",
      center: [0.5, 0],
      angle: 120,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [],
      neighbors: { R04: 3, R08: 1, T03: 0, T06: 2 },
    },
    {
      id: "R08",
      shape: "rhombus",
      center: [1, 0.8660254],
      angle: 120,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [1],
      neighbors: { R05: 0, R07: 3, R09: 2 },
    },
    {
      id: "R09",
      shape: "rhombus",
      center: [1.5, 0],
      angle: 120,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R08: 0, T06: 3 },
    },
    {
      id: "T01",
      shape: "triangle",
      center: [-1, -1.154701],
      angle: 180,
      edgeCount: 3,
      outside: [2],
      neighbors: { R01: 1, R06: 0 },
    },
    {
      id: "T02",
      shape: "triangle",
      center: [-0.3333333, 0.2886751],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { R02: 0, R04: 1, T03: 2 },
    },
    {
      id: "T03",
      shape: "triangle",
      center: [0, 0.5773503],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { R05: 1, R07: 0, T02: 2 },
    },
    {
      id: "T04",
      shape: "triangle",
      center: [0.6666667, -1.443376],
      angle: 0,
      edgeCount: 3,
      outside: [1],
      neighbors: { R06: 0, T05: 2 },
    },
    {
      id: "T05",
      shape: "triangle",
      center: [1, -1.154701],
      angle: 180,
      edgeCount: 3,
      outside: [0],
      neighbors: { T04: 2, T06: 1 },
    },
    {
      id: "T06",
      shape: "triangle",
      center: [1.166667, -0.5773503],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { R07: 0, R09: 2, T05: 1 },
    },
  ],
  pieces: [
    { id: "r-acute-1", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r-acute-2", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r-obtuse-1", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-obtuse-2", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-obtuse-3", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-straight-a", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "r-straight-b1", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "r-straight-b2", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "r-straight-b3", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "t-1", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t-2", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t-3", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t-4", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t-5", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t-6", shape: "triangle", pattern: "T1", rotations: 3 },
  ],
};
