// Level 5 - "The Sevenfold Vault"
//
// A regular side-four hexagon tiled on the triangular lattice by seven
// hexagons, twenty-one rhombi, and twelve triangles. The verified intended
// placement forms one asymmetric 40-slot loop and uses two hex plus all four
// rhombus groove patterns. The targeted verifier confirms geometry, indices,
// adjacency, hint membership, and rejection of six naive/mutated placements.
export const level5 = {
  id: "sevenfold-vault",
  number: 5,
  title: "The Sevenfold Vault",
  shortTitle: "Sevenfold Vault",
  description:
    "Seven chambers anchor a greater vault. Forty stones must carry one unbroken, deliberately uneven line.",
  board: {
    macroCenter: [0, 0],
    center: [480, 320],
    scale: 64,
    side: 4,
  },
  endpointMode: "center",
  hint: { pieceId: "h5-h3-1", slotId: "H3", rotation: 0 },
  slots: [
    {
      id: "H0",
      shape: "hex",
      center: [0, 0],
      edgeCount: 6,
      outside: [],
      neighbors: { T0: 0, T4: 1, T2: 2, T5: 3, T1: 4, T3: 5 },
    },
    {
      id: "H1",
      shape: "hex",
      center: [2, 0],
      edgeCount: 6,
      outside: [],
      neighbors: { T2: 0, R14: 1, R8: 2, T9: 3, R0: 4, T5: 5 },
    },
    {
      id: "H2",
      shape: "hex",
      center: [1, 1.732051],
      edgeCount: 6,
      outside: [],
      neighbors: { R20: 0, R12: 1, R11: 2, R14: 3, T2: 4, T4: 5 },
    },
    {
      id: "H3",
      shape: "hex",
      center: [-1, 1.732051],
      edgeCount: 6,
      outside: [],
      neighbors: { R16: 0, R1: 1, R20: 2, T4: 3, T0: 4, T7: 5 },
    },
    {
      id: "H4",
      shape: "hex",
      center: [-2, 0],
      edgeCount: 6,
      outside: [],
      neighbors: { R13: 0, T7: 1, T0: 2, T3: 3, R6: 4, R2: 5 },
    },
    {
      id: "H5",
      shape: "hex",
      center: [-1, -1.732051],
      edgeCount: 6,
      outside: [],
      neighbors: { R6: 0, T3: 1, T1: 2, R5: 3, R9: 4, R19: 5 },
    },
    {
      id: "H6",
      shape: "hex",
      center: [1, -1.732051],
      edgeCount: 6,
      outside: [],
      neighbors: { T1: 0, T5: 1, R0: 2, T11: 3, R10: 4, R5: 5 },
    },
    {
      id: "T0",
      shape: "triangle",
      center: [-1, 0.57735],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { H4: 0, H0: 1, H3: 2 },
    },
    {
      id: "T1",
      shape: "triangle",
      center: [0, -1.154701],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { H5: 0, H6: 1, H0: 2 },
    },
    {
      id: "T2",
      shape: "triangle",
      center: [1, 0.57735],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 0, H1: 1, H2: 2 },
    },
    {
      id: "T3",
      shape: "triangle",
      center: [-1, -0.57735],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H4: 0, H5: 1, H0: 2 },
    },
    {
      id: "T4",
      shape: "triangle",
      center: [0, 1.154701],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H3: 0, H0: 1, H2: 2 },
    },
    {
      id: "T5",
      shape: "triangle",
      center: [1, -0.57735],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 0, H6: 1, H1: 2 },
    },
    {
      id: "R0",
      shape: "rhombus",
      center: [2.25, -1.299038],
      angle: 0,
      edgeCount: 4,
      outside: [],
      neighbors: { T8: 0, T10: 1, H6: 2, H1: 3 },
    },
    {
      id: "R1",
      shape: "rhombus",
      center: [-0.75, 3.031089],
      angle: 60,
      edgeCount: 4,
      outside: [0],
      neighbors: { R20: 1, H3: 2, R17: 3 },
    },
    {
      id: "R2",
      shape: "rhombus",
      center: [-3, -0.866025],
      angle: 120,
      edgeCount: 4,
      outside: [3],
      neighbors: { R3: 0, H4: 1, R6: 2 },
    },
    {
      id: "T6",
      shape: "triangle",
      center: [-2.5, 1.443376],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { R13: 0, T7: 1, R16: 2 },
    },
    {
      id: "T7",
      shape: "triangle",
      center: [-2, 1.154701],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { T6: 0, H4: 1, H3: 2 },
    },
    {
      id: "R3",
      shape: "rhombus",
      center: [-3.5, 0],
      angle: 120,
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R13: 1, R2: 2 },
    },
    {
      id: "R4",
      shape: "rhombus",
      center: [1.75, -3.031089],
      angle: 60,
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { T11: 0, R10: 3 },
    },
    {
      id: "R5",
      shape: "rhombus",
      center: [0, -2.598076],
      angle: 120,
      edgeCount: 4,
      outside: [],
      neighbors: { H5: 0, H6: 1, R10: 2, R9: 3 },
    },
    {
      id: "R6",
      shape: "rhombus",
      center: [-2.25, -1.299038],
      angle: 60,
      edgeCount: 4,
      outside: [],
      neighbors: { H4: 0, H5: 1, R19: 2, R2: 3 },
    },
    {
      id: "R7",
      shape: "rhombus",
      center: [-1.75, -3.031089],
      angle: 0,
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R9: 0, R19: 3 },
    },
    {
      id: "R8",
      shape: "rhombus",
      center: [3, 0.866025],
      angle: 120,
      edgeCount: 4,
      outside: [1],
      neighbors: { R14: 0, R15: 2, H1: 3 },
    },
    {
      id: "R9",
      shape: "rhombus",
      center: [-0.75, -3.031089],
      angle: 0,
      edgeCount: 4,
      outside: [1],
      neighbors: { R5: 0, R7: 2, H5: 3 },
    },
    {
      id: "R10",
      shape: "rhombus",
      center: [0.75, -3.031089],
      angle: 60,
      edgeCount: 4,
      outside: [2],
      neighbors: { H6: 0, R4: 1, R5: 3 },
    },
    {
      id: "T8",
      shape: "triangle",
      center: [3, -1.154701],
      angle: 60,
      edgeCount: 3,
      outside: [1],
      neighbors: { R0: 0, T9: 2 },
    },
    {
      id: "T9",
      shape: "triangle",
      center: [3, -0.57735],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H1: 0, T8: 1, R15: 2 },
    },
    {
      id: "R11",
      shape: "rhombus",
      center: [2.25, 2.165064],
      angle: 0,
      edgeCount: 4,
      outside: [0],
      neighbors: { R14: 1, H2: 2, R18: 3 },
    },
    {
      id: "R12",
      shape: "rhombus",
      center: [0.75, 3.031089],
      angle: 0,
      edgeCount: 4,
      outside: [3],
      neighbors: { R18: 0, H2: 1, R20: 2 },
    },
    {
      id: "R13",
      shape: "rhombus",
      center: [-3, 0.866025],
      angle: 120,
      edgeCount: 4,
      outside: [0],
      neighbors: { T6: 1, H4: 2, R3: 3 },
    },
    {
      id: "R14",
      shape: "rhombus",
      center: [2.25, 1.299038],
      angle: 60,
      edgeCount: 4,
      outside: [],
      neighbors: { R11: 0, R8: 1, H1: 2, H2: 3 },
    },
    {
      id: "R15",
      shape: "rhombus",
      center: [3.5, 0],
      angle: 120,
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R8: 0, T9: 3 },
    },
    {
      id: "R16",
      shape: "rhombus",
      center: [-2.25, 2.165064],
      angle: 60,
      edgeCount: 4,
      outside: [3],
      neighbors: { R17: 0, H3: 1, T6: 2 },
    },
    {
      id: "R17",
      shape: "rhombus",
      center: [-1.75, 3.031089],
      angle: 60,
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R1: 1, R16: 2 },
    },
    {
      id: "R18",
      shape: "rhombus",
      center: [1.75, 3.031089],
      angle: 0,
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R11: 1, R12: 2 },
    },
    {
      id: "R19",
      shape: "rhombus",
      center: [-2.25, -2.165064],
      angle: 0,
      edgeCount: 4,
      outside: [2],
      neighbors: { H5: 0, R7: 1, R6: 3 },
    },
    {
      id: "T10",
      shape: "triangle",
      center: [2.5, -2.020726],
      angle: 60,
      edgeCount: 3,
      outside: [1],
      neighbors: { T11: 0, R0: 2 },
    },
    {
      id: "T11",
      shape: "triangle",
      center: [2, -2.309401],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H6: 0, R4: 1, T10: 2 },
    },
    {
      id: "R20",
      shape: "rhombus",
      center: [0, 2.598076],
      angle: 120,
      edgeCount: 4,
      outside: [],
      neighbors: { R1: 0, R12: 1, H2: 2, H3: 3 },
    },
  ],
  pieces: [
    { id: "r5-p1-5", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "t5-t1-1", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-ro-1", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r5-ro-6", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "h5-h1-6", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "r5-ra-3", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r5-ra-5", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r5-ra-4", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r5-p0-4", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "t5-t1-2", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-ro-3", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "t5-t1-3", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t5-t1-5", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "h5-h1-1", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "r5-ro-4", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r5-p0-1", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "r5-p1-2", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "h5-h3-1", shape: "hex", pattern: "H3", rotations: 6 },
    { id: "r5-p1-1", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "r5-ra-6", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r5-ra-1", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "h5-h1-3", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "t5-t1-6", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-p1-3", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "r5-p1-4", shape: "rhombus", pattern: "P1", rotations: 2 },
    { id: "t5-t1-4", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-p0-2", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "t5-t1-9", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-ra-2", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "t5-t1-11", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "h5-h1-5", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "r5-p0-3", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "t5-t1-12", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "t5-t1-10", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "h5-h1-2", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "t5-t1-7", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-ro-2", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "h5-h1-4", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "t5-t1-8", shape: "triangle", pattern: "T1", rotations: 3 },
    { id: "r5-ro-5", shape: "rhombus", pattern: "RO", rotations: 2 },
  ],
};
