export const level4 = {
  id: "greater-cloister",
  number: 4,
  title: "The Greater Cloister",
  shortTitle: "Greater Cloister",
  description:
    "A wider court of stone. Thirty-four fragments, one line, and no room for the eye to guess correctly.",
  board: {
    macroCenter: [0, 0],
    center: [480, 320],
    scale: 62,
    side: 3,
  },
  endpointMode: "center",
  hint: { pieceId: "h4-h1-1", slotId: "H0", rotation: 4 },
  slots: [
    {
      id: "H0",
      shape: "hex",
      center: [0, 0],
      edgeCount: 6,
      outside: [],
      neighbors: { A10: 4, A15: 3, A11: 2, A7: 1, A2: 0, A6: 5 },
    },
    {
      id: "A0",
      shape: "triangle",
      center: [-1.5, -0.288675],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { A1: 1, R14: 2, A6: 0 },
    },
    {
      id: "A1",
      shape: "triangle",
      center: [-1.5, 0.288675],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A0: 1, A2: 2, R1: 0 },
    },
    {
      id: "A2",
      shape: "triangle",
      center: [-1, 0.57735],
      angle: 300,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 2, A1: 1, A3: 0 },
    },
    {
      id: "A3",
      shape: "triangle",
      center: [-1, 1.154701],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A2: 1, A4: 2, R2: 0 },
    },
    {
      id: "A4",
      shape: "triangle",
      center: [-0.5, 1.443376],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { A3: 2, R3: 1, A7: 0 },
    },
    {
      id: "A5",
      shape: "triangle",
      center: [-1, -1.154701],
      angle: 300,
      edgeCount: 3,
      outside: [],
      neighbors: { A6: 0, R13: 1, A9: 2 },
    },
    {
      id: "A6",
      shape: "triangle",
      center: [-1, -0.57735],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 2, A0: 0, A5: 1 },
    },
    {
      id: "A7",
      shape: "triangle",
      center: [0, 1.154701],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 1, A4: 0, A8: 2 },
    },
    {
      id: "A8",
      shape: "triangle",
      center: [0.5, 1.443376],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { A7: 2, R4: 1, A12: 0 },
    },
    {
      id: "A9",
      shape: "triangle",
      center: [-0.5, -1.443376],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A5: 0, R12: 1, A10: 2 },
    },
    {
      id: "A10",
      shape: "triangle",
      center: [0, -1.154701],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 1, A9: 2, A13: 0 },
    },
    {
      id: "A11",
      shape: "triangle",
      center: [1, 0.57735],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 0, A12: 2, A17: 1 },
    },
    {
      id: "A12",
      shape: "triangle",
      center: [1, 1.154701],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A8: 0, A11: 1, R6: 2 },
    },
    {
      id: "A13",
      shape: "triangle",
      center: [0.5, -1.443376],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A10: 0, R11: 1, A14: 2 },
    },
    {
      id: "A14",
      shape: "triangle",
      center: [1, -1.154701],
      angle: 60,
      edgeCount: 3,
      outside: [],
      neighbors: { A13: 0, A15: 2, R9: 1 },
    },
    {
      id: "A15",
      shape: "triangle",
      center: [1, -0.57735],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { H0: 0, A14: 1, A16: 2 },
    },
    {
      id: "A16",
      shape: "triangle",
      center: [1.5, -0.288675],
      angle: 180,
      edgeCount: 3,
      outside: [],
      neighbors: { A15: 2, A17: 1, R8: 0 },
    },
    {
      id: "A17",
      shape: "triangle",
      center: [1.5, 0.288675],
      angle: 0,
      edgeCount: 3,
      outside: [],
      neighbors: { A11: 0, A16: 1, R7: 2 },
    },
    {
      id: "R0",
      shape: "rhombus",
      center: [-2.5, 0],
      angle: 300,
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R14: 0, R1: 3 },
    },
    {
      id: "R1",
      shape: "rhombus",
      center: [-2, 0.866025],
      angle: 300,
      edgeCount: 4,
      outside: [2],
      neighbors: { A1: 0, R0: 1, R2: 3 },
    },
    {
      id: "R2",
      shape: "rhombus",
      center: [-1.5, 1.732051],
      angle: 120,
      edgeCount: 4,
      outside: [0],
      neighbors: { A3: 2, R1: 3, R3: 1 },
    },
    {
      id: "R3",
      shape: "rhombus",
      center: [-0.75, 2.165064],
      angle: 0,
      edgeCount: 4,
      outside: [3],
      neighbors: { A4: 1, R2: 2, R4: 0 },
    },
    {
      id: "R4",
      shape: "rhombus",
      center: [0.25, 2.165064],
      angle: 0,
      edgeCount: 4,
      outside: [3],
      neighbors: { A8: 1, R3: 2, R5: 0 },
    },
    {
      id: "R5",
      shape: "rhombus",
      center: [1.25, 2.165064],
      angle: 0,
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R4: 2, R6: 1 },
    },
    {
      id: "R6",
      shape: "rhombus",
      center: [1.75, 1.299038],
      angle: 0,
      edgeCount: 4,
      outside: [0],
      neighbors: { A12: 2, R5: 3, R7: 1 },
    },
    {
      id: "R7",
      shape: "rhombus",
      center: [2.25, 0.433013],
      angle: 0,
      edgeCount: 4,
      outside: [0],
      neighbors: { A17: 2, R6: 3, R8: 1 },
    },
    {
      id: "R8",
      shape: "rhombus",
      center: [2.25, -0.433013],
      angle: 240,
      edgeCount: 4,
      outside: [3],
      neighbors: { A16: 1, R7: 2, R9: 0 },
    },
    {
      id: "R9",
      shape: "rhombus",
      center: [1.75, -1.299038],
      angle: 60,
      edgeCount: 4,
      outside: [1],
      neighbors: { A14: 3, R8: 0, R10: 2 },
    },
    {
      id: "R10",
      shape: "rhombus",
      center: [1.25, -2.165064],
      angle: 60,
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R9: 0, R11: 3 },
    },
    {
      id: "R11",
      shape: "rhombus",
      center: [0.25, -2.165064],
      angle: 60,
      edgeCount: 4,
      outside: [2],
      neighbors: { A13: 0, R10: 1, R12: 3 },
    },
    {
      id: "R12",
      shape: "rhombus",
      center: [-0.75, -2.165064],
      angle: 60,
      edgeCount: 4,
      outside: [2],
      neighbors: { A9: 0, R11: 1, R13: 3 },
    },
    {
      id: "R13",
      shape: "rhombus",
      center: [-1.5, -1.732051],
      angle: 120,
      edgeCount: 4,
      outside: [3],
      neighbors: { A5: 1, R12: 2, R14: 0 },
    },
    {
      id: "R14",
      shape: "rhombus",
      center: [-2, -0.866025],
      angle: 300,
      edgeCount: 4,
      outside: [1],
      neighbors: { A0: 3, R0: 2, R13: 0 },
    },
  ],
  pieces: [
  { id: "h4-h1-1", shape: "hex", pattern: "H1", rotations: 6 },
  { id: "t4-t1-1", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-2", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-3", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-4", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-5", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-6", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-7", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-8", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-9", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-10", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-11", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-12", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-13", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-14", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-15", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-16", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-17", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "t4-t1-18", shape: "triangle", pattern: "T1", rotations: 3 },
  { id: "r4-ro-1", shape: "rhombus", pattern: "RO", rotations: 2 },
  { id: "r4-p1-2", shape: "rhombus", pattern: "P1", rotations: 2 },
  { id: "r4-ra-3", shape: "rhombus", pattern: "RA", rotations: 2 },
  { id: "r4-ra-4", shape: "rhombus", pattern: "RA", rotations: 2 },
  { id: "r4-p0-5", shape: "rhombus", pattern: "P0", rotations: 2 },
  { id: "r4-ro-6", shape: "rhombus", pattern: "RO", rotations: 2 },
  { id: "r4-p1-7", shape: "rhombus", pattern: "P1", rotations: 2 },
  { id: "r4-p1-8", shape: "rhombus", pattern: "P1", rotations: 2 },
  { id: "r4-p0-9", shape: "rhombus", pattern: "P0", rotations: 2 },
  { id: "r4-p0-10", shape: "rhombus", pattern: "P0", rotations: 2 },
  { id: "r4-ro-11", shape: "rhombus", pattern: "RO", rotations: 2 },
  { id: "r4-p1-12", shape: "rhombus", pattern: "P1", rotations: 2 },
  { id: "r4-ra-13", shape: "rhombus", pattern: "RA", rotations: 2 },
  { id: "r4-ra-14", shape: "rhombus", pattern: "RA", rotations: 2 },
  { id: "r4-p0-15", shape: "rhombus", pattern: "P0", rotations: 2 },
  ],
};
