export const level2 = {
  id: "fifteen-stones",
  number: 2,
  title: "The Fifteen Stones",
  shortTitle: "Fifteen Stones",
  description:
    "A larger field, and a line that can deceive. Reject the closed fragments; only one circuit may remain.",
  board: {
    macroCenter: [2, 0],
    center: [480, 320],
    scale: 88,
    side: 3,
  },
  endpointMode: "center",
  hint: { pieceId: "h-1", slotId: "H0", rotation: 2 },
  slots: [
    {
      id: "H0",
      shape: "hex",
      center: [0, 0],
      edgeCount: 6,
      outside: [0, 5],
      neighbors: { H1: 2, H3: 3, R0: 4, R2: 1 },
    },
    {
      id: "H1",
      shape: "hex",
      center: [1.5, 0.866],
      edgeCount: 6,
      outside: [],
      neighbors: { H0: 5, H2: 2, H3: 4, H4: 3, R2: 0, R5: 1 },
    },
    {
      id: "H2",
      shape: "hex",
      center: [3, 1.732],
      edgeCount: 6,
      outside: [1, 2],
      neighbors: { H1: 5, H4: 4, R5: 0, R7: 3 },
    },
    {
      id: "H3",
      shape: "hex",
      center: [1.5, -0.866],
      edgeCount: 6,
      outside: [],
      neighbors: { H0: 0, H1: 1, H4: 2, H5: 3, R0: 5, R3: 4 },
    },
    {
      id: "H4",
      shape: "hex",
      center: [3, 0],
      edgeCount: 6,
      outside: [],
      neighbors: { H1: 0, H2: 1, H3: 5, H5: 4, R6: 3, R7: 2 },
    },
    {
      id: "H5",
      shape: "hex",
      center: [3, -1.732],
      edgeCount: 6,
      outside: [3, 4],
      neighbors: { H3: 0, H4: 1, R3: 5, R6: 2 },
    },
    {
      id: "R0",
      shape: "rhombus",
      center: [0.25, -1.299],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [2],
      neighbors: { H0: 3, H3: 0, R1: 1 },
    },
    {
      id: "R1",
      shape: "rhombus",
      center: [0.75, -2.165],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R0: 3, R3: 0 },
    },
    {
      id: "R2",
      shape: "rhombus",
      center: [0.25, 1.299],
      angle: -120,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [3],
      neighbors: { H0: 2, H1: 1, R4: 0 },
    },
    {
      id: "R3",
      shape: "rhombus",
      center: [1.75, -2.165],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [1],
      neighbors: { H3: 3, H5: 0, R1: 2 },
    },
    {
      id: "R4",
      shape: "rhombus",
      center: [0.75, 2.165],
      angle: -120,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { R2: 2, R5: 1 },
    },
    {
      id: "R5",
      shape: "rhombus",
      center: [1.75, 2.165],
      angle: -120,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [0],
      neighbors: { H1: 2, H2: 1, R4: 3 },
    },
    {
      id: "R6",
      shape: "rhombus",
      center: [4, -0.866],
      angle: -60,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [2],
      neighbors: { H4: 0, H5: 3, R8: 1 },
    },
    {
      id: "R7",
      shape: "rhombus",
      center: [4, 0.866],
      angle: -60,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [1],
      neighbors: { H2: 0, H4: 3, R8: 2 },
    },
    {
      id: "R8",
      shape: "rhombus",
      center: [4.5, 0],
      angle: -60,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { R6: 3, R7: 0 },
    },
  ],
  pieces: [
    { id: "h-1", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "h-2", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "h-3", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "h-4", shape: "hex", pattern: "H1", rotations: 6 },
    { id: "h-5", shape: "hex", pattern: "H2", rotations: 6 },
    { id: "h-6", shape: "hex", pattern: "H3", rotations: 6 },
    { id: "r-acute-1", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r-acute-2", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r-acute-3", shape: "rhombus", pattern: "RA", rotations: 2 },
    { id: "r-obtuse-1", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-obtuse-2", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-obtuse-3", shape: "rhombus", pattern: "RO", rotations: 2 },
    { id: "r-parallel-a", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "r-parallel-b", shape: "rhombus", pattern: "P0", rotations: 2 },
    { id: "r-parallel-c", shape: "rhombus", pattern: "P1", rotations: 2 },
  ],
};
