export const level1 = {
  id: "threefold-gate",
  number: 1,
  title: "The Threefold Gate",
  shortTitle: "Threefold Gate",
  description:
    "Three blue stones and three ochre stones. The outer edge is silent; let the inner path return to itself.",
  board: {
    macroCenter: [1, 0],
    center: [500, 330],
    scale: 138,
    side: 2,
  },
  endpointMode: "center",
  matchingMode: "complement",
  hint: { pieceId: "h-quiet", slotId: "H0", rotation: 1 },
  slots: [
    {
      id: "H0",
      shape: "hex",
      center: [0, 0],
      edgeCount: 6,
      outside: [0, 5],
      neighbors: { H1: 2, H2: 3, R0: 4, R1: 1 },
    },
    {
      id: "H1",
      shape: "hex",
      center: [1.5, 0.866],
      edgeCount: 6,
      outside: [1, 2],
      neighbors: { H0: 5, H2: 4, R1: 0, R2: 3 },
    },
    {
      id: "H2",
      shape: "hex",
      center: [1.5, -0.866],
      edgeCount: 6,
      outside: [3, 4],
      neighbors: { H0: 0, H1: 1, R0: 5, R2: 2 },
    },
    {
      id: "R0",
      shape: "rhombus",
      center: [0.25, -1.299],
      angle: 0,
      edgeMap: [0, 1, 2, 3],
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { H0: 3, H2: 0 },
    },
    {
      id: "R1",
      shape: "rhombus",
      center: [0.25, 1.299],
      angle: -120,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [0, 3],
      neighbors: { H0: 2, H1: 1 },
    },
    {
      id: "R2",
      shape: "rhombus",
      center: [2.5, 0],
      angle: -60,
      edgeMap: [2, 3, 0, 1],
      edgeCount: 4,
      outside: [1, 2],
      neighbors: { H1: 0, H2: 3 },
    },
  ],
  pieces: [
    { id: "h-quiet", shape: "hex", pattern: "H3", bits: [0, 0], rotations: 6 },
    { id: "h-waking", shape: "hex", pattern: "H3", bits: [0, 1], rotations: 6 },
    { id: "h-lucent", shape: "hex", pattern: "H3", bits: [1, 1], rotations: 6 },
    { id: "r-quiet", shape: "rhombus", pattern: "RO", bits: [0, 0], rotations: 2 },
    { id: "r-waking", shape: "rhombus", pattern: "RO", bits: [0, 1], rotations: 2 },
    { id: "r-lucent", shape: "rhombus", pattern: "RO", bits: [1, 1], rotations: 2 },
  ],
};
